// generated by gotemplate

package opt

import (
	"fmt"

	"github.com/CosmWasm/tinyjson/jlexer"
	"github.com/CosmWasm/tinyjson/jwriter"
)

// template type Optional(A)

// A 'gotemplate'-based type for providing optional semantics without using pointers.
type Int8 struct {
	V       int8
	Defined bool
}

// Creates an optional type with a given value.
func OInt8(v int8) Int8 {
	return Int8{V: v, Defined: true}
}

// Get returns the value or given default in the case the value is undefined.
func (v Int8) Get(deflt int8) int8 {
	if !v.Defined {
		return deflt
	}
	return v.V
}

// MarshalTinyJSON does JSON marshaling using tinyjson interface.
func (v Int8) MarshalTinyJSON(w *jwriter.Writer) {
	if v.Defined {
		w.Int8(v.V)
	} else {
		w.RawString("null")
	}
}

// UnmarshalTinyJSON does JSON unmarshaling using tinyjson interface.
func (v *Int8) UnmarshalTinyJSON(l *jlexer.Lexer) {
	if l.IsNull() {
		l.Skip()
		*v = Int8{}
	} else {
		v.V = l.Int8()
		v.Defined = true
	}
}

// MarshalJSON implements a standard json marshaler interface.
func (v Int8) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// UnmarshalJSON implements a standard json unmarshaler interface.
func (v *Int8) UnmarshalJSON(data []byte) error {
	l := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&l)
	return l.Error()
}

// IsDefined returns whether the value is defined, a function is required so that it can
// be used in an interface.
func (v Int8) IsDefined() bool {
	return v.Defined
}

// String implements a stringer interface using fmt.Sprint for the value.
func (v Int8) String() string {
	if !v.Defined {
		return "<undefined>"
	}
	return fmt.Sprint(v.V)
}
