// generated by gotemplate

package opt

import (
	"fmt"

	"github.com/CosmWasm/tinyjson/jlexer"
	"github.com/CosmWasm/tinyjson/jwriter"
)

// template type Optional(A)

// A 'gotemplate'-based type for providing optional semantics without using pointers.
type Uint8 struct {
	V       uint8
	Defined bool
}

// Creates an optional type with a given value.
func OUint8(v uint8) Uint8 {
	return Uint8{V: v, Defined: true}
}

// Get returns the value or given default in the case the value is undefined.
func (v Uint8) Get(deflt uint8) uint8 {
	if !v.Defined {
		return deflt
	}
	return v.V
}

// MarshalTinyJSON does JSON marshaling using tinyjson interface.
func (v Uint8) MarshalTinyJSON(w *jwriter.Writer) {
	if v.Defined {
		w.Uint8(v.V)
	} else {
		w.RawString("null")
	}
}

// UnmarshalTinyJSON does JSON unmarshaling using tinyjson interface.
func (v *Uint8) UnmarshalTinyJSON(l *jlexer.Lexer) {
	if l.IsNull() {
		l.Skip()
		*v = Uint8{}
	} else {
		v.V = l.Uint8()
		v.Defined = true
	}
}

// MarshalJSON implements a standard json marshaler interface.
func (v Uint8) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	v.MarshalTinyJSON(&w)
	return w.Buffer.BuildBytes(), w.Error
}

// UnmarshalJSON implements a standard json unmarshaler interface.
func (v *Uint8) UnmarshalJSON(data []byte) error {
	l := jlexer.Lexer{Data: data}
	v.UnmarshalTinyJSON(&l)
	return l.Error()
}

// IsDefined returns whether the value is defined, a function is required so that it can
// be used in an interface.
func (v Uint8) IsDefined() bool {
	return v.Defined
}

// String implements a stringer interface using fmt.Sprint for the value.
func (v Uint8) String() string {
	if !v.Defined {
		return "<undefined>"
	}
	return fmt.Sprint(v.V)
}
